### PR TITLE
Update README to use Octane patterns

### PR DESCRIPTION
**Pull request by viniciussbs**
Hi! You've told me that you wanted to update the README. Is this OK?

### CODE REVIEW

**Comment by alexlafroscia** [comment]
Thanks! This is great!

I think the use-case for this addon is mostly like JS-less components, so the action being wrapped will most likely be an argument instead of something local. That was the other change I had in mind!

**Comment by viniciussbs** [comment]
Are you talking about the `@action` decorator and `action` helpers?

If that's the case, I guess this won't be a problem since the action is decorated when you need to access the scope of `this`, right? Since there is no JS class, there will be nothing in `this` to look at.

Actually, we should not put `this.someAction` in the example, since there will be no action defined in JS, so we should not use `this`. Maybe use a function from a service as an example?

```handlebars
{{#let (wrap-in-task someService.someFunction) as |task|}}
  <button {{on "click" (perform task)}} disabled={{task.isRunning}}>
    {{if task.isRunning "Running..." "Run"}}
  </button>
{{/let}}
```

I don't use Ember Data, so I can't tell this would work:

```handlebars
{{#let (wrap-in-task @user.save) as |saveUser|}}
  <form {{on "submit" saveUser}}>
    ...
    <button type="submit" disabled={{saveUser.isRunning}}>
      {{if saveUser.isRunning "Saving..." "Save"}}
    </button>
  </form>
{{/let}}
```

Is this beyond what you were thinking?

**Comment by alexlafroscia** [comment]
I'm thinking this

```hbs
{{#let (wrap-in-task @someArgumentFunction) as |task|}}
  <button {{on "click" (perform task)}} disabled={{task.isRunning}}>
    {{if task.isRunning "Running..." "Run"}}
  </button>
{{/let}}
```

Which seems to be like the strongest use-case for this addon (defining a task in HBS that wraps an action that could be async, if you need to know that the async task is in the process of running).

**Comment by viniciussbs** [comment]
Nice! I've updated the PR with your example.

**Comment by alexlafroscia** [comment]
Thanks so much for updating this, @viniciussbs !

**Pull request merged**
